import { useEffect, useState } from "react";
import Head from "next/head";
import { ConnectButton } from "@web3uikit/web3";
import { useMoralis, useWeb3Contract } from "react-moralis";
// ---internal import
import styles from "@/styles/Home.module.css";
import { ContractAddresses, Abi } from "@/constants/constantIndex";

export default function Home() {
  const { isWeb3Enabled } = useMoralis();
  const [characterNft, setCharacterNft] = useState(false);
  // const [characterIndex, setCharacterIndex] = useState(0);

  const { runContractFunction: checkIfUserHasNFT } = useWeb3Contract({
    contractAddress: ContractAddresses[5][0],
    abi: Abi,
    functionName: "mintCharacterNFT",
    params: {},
  });

  useEffect(() => {
    async function callContract() {
      const object = await checkIfUserHasNFT();
      console.log(object);
    }
    callContract();
  }, []);

  async function handleClick(index) {
    const { runContractFunction: mintCharacterNFT } = useWeb3Contract({
      contractAddress: ContractAddresses[5][0],
      abi: Abi,
      functionName: "mintCharacterNFT",
      params: {
        _characterIndex: index,
      },
    });
  }

  return (
    <>
      <Head>
        <title>Epic Game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.home}>
          <div className={styles.home_container}>
            <h1>⚔️ Metaverse Slayer ⚔️</h1>
            <p>Team up to protect the Metaverse!</p>
            {!isWeb3Enabled && !characterNft ? (
              <div>
                <img
                  src="https://64.media.tumblr.com/tumblr_mbia5vdmRd1r1mkubo1_500.gifv"
                  // height={300}
                  // width={300}
                  alt="prince gif"
                />
                <p> Connect Wallet to get started</p>
                <ConnectButton />
              </div>
            ) : isWeb3Enabled && !characterNft ? (
              <div className={styles.home_characters}>
                <h3> Choose the character to mint </h3>
                <div className={styles.home_characters_box}>
                  <img
                    src="https://i.imgur.com/pKd5Sdk.png"
                    alt="leo image"
                    height={300}
                    width={300}
                    onClick={() => handleClick(0)}
                  />
                  <img
                    src="https://i.imgur.com/xVu4vFL.png"
                    alt="leo image"
                    height={300}
                    width={300}
                    onClick={() => handleClick(1)}
                  />
                  <img
                    src="https://i.imgur.com/WMB6g9u.png"
                    alt="leo image"
                    height={300}
                    width={300}
                    onClick={() => handleClick(2)}
                  />
                </div>
              </div>
            ) : (
              (isWeb3Enabled && characterNft)(
                <div>
                  <h1>my name is prince sharma</h1>
                </div>
              )
            )}
          </div>
        </div>
      </main>
    </>
  );
}
