import { useEffect, useState } from "react";
import Head from "next/head";
import { useMoralis, useWeb3Contract } from "react-moralis";
// ---internal import
import styles from "@/styles/Home.module.css";
import { ContractAddresses, Abi } from "@/constants/constantIndex";
import CharacterNft from "@/components/CharacterNft/CharacterNft";
import Image from "next/image";
import images from "../img/imgIndex";

export default function Home() {
  const { isWeb3Enabled, chainId: chainIdHex, account } = useMoralis();
  const [characterNft, setCharacterNft] = useState(false);
  const chainId = parseInt(chainIdHex);

  const marketplaceAddress =
    chainId in ContractAddresses ? ContractAddresses[chainId][0] : null;

  const { runContractFunction: checkIfUserHasNFT } = useWeb3Contract({
    contractAddress: marketplaceAddress,
    abi: Abi,
    functionName: "checkIfUserHasNFT",
    params: {},
  });

  useEffect(() => {
    async function callContract() {
      await checkIfUserHasNFT();
      setCharacterNft(true);
      console.log(marketplaceAddress);
    }
    callContract();
  }, []);

  return (
    <>
      <Head>
        <title>Epic Game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.home}>
          <div className={styles.home_container}>
            <p>Team up to protect the Metaverse!</p>
            {!isWeb3Enabled ? (
              <div className={styles.home_container_box}>
                <Image
                  src={images.poster}
                  alt="Marvel's poster"
                  height={600}
                  width={800}
                  className={styles.home_container_box_img}
                />
                <p> Connect Wallet to get started</p>
              </div>
            ) : (
              <CharacterNft marketplaceAddress={marketplaceAddress} />
            )}
          </div>
        </div>
      </main>
    </>
  );
}
